# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configuration_wdgt_main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from mnemosyne.libmnemosyne.translator import _
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigurationWdgtMain(object):
    def setupUi(self, ConfigurationWdgtMain):
        ConfigurationWdgtMain.setObjectName("ConfigurationWdgtMain")
        ConfigurationWdgtMain.resize(457, 375)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(ConfigurationWdgtMain)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtWidgets.QGroupBox(ConfigurationWdgtMain)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.new_cards = QtWidgets.QComboBox(self.groupBox)
        self.new_cards.setObjectName("new_cards")
        self.new_cards.addItem("")
        self.new_cards.addItem("")
        self.horizontalLayout_2.addWidget(self.new_cards)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.scheduled_cards = QtWidgets.QComboBox(self.groupBox)
        self.scheduled_cards.setObjectName("scheduled_cards")
        self.scheduled_cards.addItem("")
        self.scheduled_cards.addItem("")
        self.horizontalLayout_3.addWidget(self.scheduled_cards)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.non_memorised_cards = QtWidgets.QSpinBox(self.groupBox)
        self.non_memorised_cards.setMinimum(1)
        self.non_memorised_cards.setProperty("value", 10)
        self.non_memorised_cards.setObjectName("non_memorised_cards")
        self.horizontalLayout.addWidget(self.non_memorised_cards)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.save_after_n_reps = QtWidgets.QSpinBox(self.groupBox)
        self.save_after_n_reps.setMinimum(1)
        self.save_after_n_reps.setMaximum(25)
        self.save_after_n_reps.setProperty("value", 10)
        self.save_after_n_reps.setObjectName("save_after_n_reps")
        self.horizontalLayout_4.addWidget(self.save_after_n_reps)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.audio_box = QtWidgets.QGroupBox(ConfigurationWdgtMain)
        self.audio_box.setObjectName("audio_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.audio_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.media_autoplay = QtWidgets.QCheckBox(self.audio_box)
        self.media_autoplay.setChecked(True)
        self.media_autoplay.setObjectName("media_autoplay")
        self.verticalLayout_2.addWidget(self.media_autoplay)
        self.media_controls = QtWidgets.QCheckBox(self.audio_box)
        self.media_controls.setChecked(False)
        self.media_controls.setObjectName("media_controls")
        self.verticalLayout_2.addWidget(self.media_controls)
        self.verticalLayout_5.addWidget(self.audio_box)
        self.groupBox_3 = QtWidgets.QGroupBox(ConfigurationWdgtMain)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.upload_science_logs = QtWidgets.QCheckBox(self.groupBox_3)
        self.upload_science_logs.setChecked(True)
        self.upload_science_logs.setObjectName("upload_science_logs")
        self.verticalLayout_3.addWidget(self.upload_science_logs)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(ConfigurationWdgtMain)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.languages = QtWidgets.QComboBox(self.groupBox_4)
        self.languages.setObjectName("languages")
        self.verticalLayout_4.addWidget(self.languages)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)

        self.retranslateUi(ConfigurationWdgtMain)
        QtCore.QMetaObject.connectSlotsByName(ConfigurationWdgtMain)

    def retranslateUi(self, ConfigurationWdgtMain):
        _translate = QtCore.QCoreApplication.translate
        ConfigurationWdgtMain.setWindowTitle(_('Form'))
        self.groupBox.setTitle(_('Scheduler'))
        self.label_2.setText(_('Show new cards for the first time'))
        self.new_cards.setItemText(0, _('in the order they were added'))
        self.new_cards.setItemText(1, _('in random order'))
        self.label_3.setText(_('Review memorised cards'))
        self.scheduled_cards.setItemText(0, _('most urgent first'))
        self.scheduled_cards.setItemText(1, _('in random order'))
        self.label.setText(_('Hold'))
        self.label_4.setText(_('non-memorised cards in your hand'))
        self.label_5.setText(_('Autosave after'))
        self.label_6.setText(_('repetitions'))
        self.audio_box.setTitle(_('Audio/video'))
        self.media_autoplay.setText(_('Start automatically when displaying card'))
        self.media_controls.setText(_('Show controls (pause, ...)'))
        self.groupBox_3.setTitle(_('Science'))
        self.upload_science_logs.setText(_('Upload anonymous science logs'))
        self.groupBox_4.setTitle(_('Language'))

