# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'import_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from mnemosyne.libmnemosyne.translator import _
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ImportDlg(object):
    def setupUi(self, ImportDlg):
        ImportDlg.setObjectName("ImportDlg")
        ImportDlg.resize(251, 185)
        self.gridLayout = QtWidgets.QGridLayout(ImportDlg)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.vboxlayout = QtWidgets.QVBoxLayout()
        self.vboxlayout.setContentsMargins(11, 11, 11, 11)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.textLabel_5 = QtWidgets.QLabel(ImportDlg)
        self.textLabel_5.setWordWrap(False)
        self.textLabel_5.setObjectName("textLabel_5")
        self.vboxlayout.addWidget(self.textLabel_5)
        self.file_formats = QtWidgets.QComboBox(ImportDlg)
        self.file_formats.setEditable(False)
        self.file_formats.setDuplicatesEnabled(False)
        self.file_formats.setObjectName("file_formats")
        self.vboxlayout.addWidget(self.file_formats)
        self.textLabel1 = QtWidgets.QLabel(ImportDlg)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.vboxlayout.addWidget(self.textLabel1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(11, 11, 11, 11)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.filename_box = QtWidgets.QLineEdit(ImportDlg)
        self.filename_box.setObjectName("filename_box")
        self.hboxlayout.addWidget(self.filename_box)
        self.browse_button = QtWidgets.QPushButton(ImportDlg)
        self.browse_button.setObjectName("browse_button")
        self.hboxlayout.addWidget(self.browse_button)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.textLabel2 = QtWidgets.QLabel(ImportDlg)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.vboxlayout.addWidget(self.textLabel2)
        self.tags = QtWidgets.QComboBox(ImportDlg)
        self.tags.setEditable(True)
        self.tags.setDuplicatesEnabled(False)
        self.tags.setObjectName("tags")
        self.vboxlayout.addWidget(self.tags)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setContentsMargins(11, 11, 11, 11)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.ok_button = QtWidgets.QPushButton(ImportDlg)
        self.ok_button.setDefault(True)
        self.ok_button.setObjectName("ok_button")
        self.hboxlayout1.addWidget(self.ok_button)
        spacerItem = QtWidgets.QSpacerItem(201, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.cancel_button = QtWidgets.QPushButton(ImportDlg)
        self.cancel_button.setDefault(False)
        self.cancel_button.setObjectName("cancel_button")
        self.hboxlayout1.addWidget(self.cancel_button)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.gridLayout.addLayout(self.vboxlayout, 0, 0, 1, 1)

        self.retranslateUi(ImportDlg)
        self.cancel_button.clicked.connect(ImportDlg.reject)
        self.browse_button.clicked.connect(ImportDlg.browse)
        self.ok_button.clicked.connect(ImportDlg.accept)
        self.file_formats.currentIndexChanged['int'].connect(ImportDlg.file_format_changed)
        QtCore.QMetaObject.connectSlotsByName(ImportDlg)
        ImportDlg.setTabOrder(self.filename_box, self.browse_button)
        ImportDlg.setTabOrder(self.browse_button, self.file_formats)
        ImportDlg.setTabOrder(self.file_formats, self.tags)
        ImportDlg.setTabOrder(self.tags, self.ok_button)
        ImportDlg.setTabOrder(self.ok_button, self.cancel_button)

    def retranslateUi(self, ImportDlg):
        _translate = QtCore.QCoreApplication.translate
        ImportDlg.setWindowTitle(_('Import from file'))
        self.textLabel_5.setText(_('File format:'))
        self.textLabel1.setText(_('File to import from:'))
        self.browse_button.setText(_('&Browse'))
        self.textLabel2.setText(_('Add additional tag(s) to cards:'))
        self.ok_button.setText(_('&OK'))
        self.ok_button.setShortcut(_('Alt+O'))
        self.cancel_button.setText(_('&Cancel'))

