# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_wdgt.ui'
#
# Created: Mon Apr 15 14:30:13 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from mnemosyne.libmnemosyne.translator import _
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWdgt(object):
    def setupUi(self, MainWdgt):
        MainWdgt.setObjectName(_fromUtf8("MainWdgt"))
        MainWdgt.resize(315, 494)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWdgt.sizePolicy().hasHeightForWidth())
        MainWdgt.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/mnemosyne.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWdgt.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWdgt)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWdgt.setCentralWidget(self.centralwidget)
        self.menu_bar = QtGui.QMenuBar(MainWdgt)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 315, 21))
        self.menu_bar.setObjectName(_fromUtf8("menu_bar"))
        self.menu_Settings = QtGui.QMenu(self.menu_bar)
        self.menu_Settings.setObjectName(_fromUtf8("menu_Settings"))
        self.menu_Help = QtGui.QMenu(self.menu_bar)
        self.menu_Help.setObjectName(_fromUtf8("menu_Help"))
        self.menuFile = QtGui.QMenu(self.menu_bar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menu_Cards = QtGui.QMenu(self.menu_bar)
        self.menu_Cards.setObjectName(_fromUtf8("menu_Cards"))
        MainWdgt.setMenuBar(self.menu_bar)
        self.status_bar = QtGui.QStatusBar(MainWdgt)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        MainWdgt.setStatusBar(self.status_bar)
        self.tool_bar = QtGui.QToolBar(MainWdgt)
        self.tool_bar.setMovable(False)
        self.tool_bar.setIconSize(QtCore.QSize(22, 22))
        self.tool_bar.setFloatable(False)
        self.tool_bar.setObjectName(_fromUtf8("tool_bar"))
        MainWdgt.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)
        self.actionActivateCards = QtGui.QAction(MainWdgt)
        self.actionActivateCards.setObjectName(_fromUtf8("actionActivateCards"))
        self.actionAddCards = QtGui.QAction(MainWdgt)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAddCards.setIcon(icon1)
        self.actionAddCards.setObjectName(_fromUtf8("actionAddCards"))
        self.actionConfigure = QtGui.QAction(MainWdgt)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/configure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigure.setIcon(icon2)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionDeleteCurrentCard = QtGui.QAction(MainWdgt)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDeleteCurrentCard.setIcon(icon3)
        self.actionDeleteCurrentCard.setObjectName(_fromUtf8("actionDeleteCurrentCard"))
        self.actionEditCurrentCard = QtGui.QAction(MainWdgt)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditCurrentCard.setIcon(icon4)
        self.actionEditCurrentCard.setObjectName(_fromUtf8("actionEditCurrentCard"))
        self.actionBrowseCards = QtGui.QAction(MainWdgt)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/cards.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBrowseCards.setIcon(icon5)
        self.actionBrowseCards.setObjectName(_fromUtf8("actionBrowseCards"))
        self.actionExport = QtGui.QAction(MainWdgt)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionFileExit = QtGui.QAction(MainWdgt)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileExit.setIcon(icon6)
        self.actionFileExit.setObjectName(_fromUtf8("actionFileExit"))
        self.actionFileNew = QtGui.QAction(MainWdgt)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../../pixmaps/filenew.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileNew.setIcon(icon7)
        self.actionFileNew.setObjectName(_fromUtf8("actionFileNew"))
        self.actionFileOpen = QtGui.QAction(MainWdgt)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/fileopen.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileOpen.setIcon(icon8)
        self.actionFileOpen.setObjectName(_fromUtf8("actionFileOpen"))
        self.actionFileSave = QtGui.QAction(MainWdgt)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/filesave.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileSave.setIcon(icon9)
        self.actionFileSave.setObjectName(_fromUtf8("actionFileSave"))
        self.actionFileSaveAs = QtGui.QAction(MainWdgt)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/filesaveas.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFileSaveAs.setIcon(icon10)
        self.actionFileSaveAs.setObjectName(_fromUtf8("actionFileSaveAs"))
        self.actionAbout = QtGui.QAction(MainWdgt)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionImport = QtGui.QAction(MainWdgt)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionGettingStarted = QtGui.QAction(MainWdgt)
        self.actionGettingStarted.setObjectName(_fromUtf8("actionGettingStarted"))
        self.actionShowStatistics = QtGui.QAction(MainWdgt)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/mnemosyne/pixmaps/statistics.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionShowStatistics.setIcon(icon11)
        self.actionShowStatistics.setObjectName(_fromUtf8("actionShowStatistics"))
        self.actionTip = QtGui.QAction(MainWdgt)
        self.actionTip.setObjectName(_fromUtf8("actionTip"))
        self.actionManagePlugins = QtGui.QAction(MainWdgt)
        self.actionManagePlugins.setObjectName(_fromUtf8("actionManagePlugins"))
        self.actionManageTypes = QtGui.QAction(MainWdgt)
        self.actionManageTypes.setObjectName(_fromUtf8("actionManageTypes"))
        self.actionSync = QtGui.QAction(MainWdgt)
        self.actionSync.setObjectName(_fromUtf8("actionSync"))
        self.actionCompact = QtGui.QAction(MainWdgt)
        self.actionCompact.setObjectName(_fromUtf8("actionCompact"))
        self.actionFindDuplicates = QtGui.QAction(MainWdgt)
        self.actionFindDuplicates.setObjectName(_fromUtf8("actionFindDuplicates"))
        self.menu_Settings.addAction(self.actionConfigure)
        self.menu_Settings.addAction(self.actionManagePlugins)
        self.menu_Help.addAction(self.actionGettingStarted)
        self.menu_Help.addAction(self.actionTip)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionFileNew)
        self.menuFile.addAction(self.actionFileOpen)
        self.menuFile.addAction(self.actionFileSave)
        self.menuFile.addAction(self.actionFileSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionSync)
        self.menuFile.addAction(self.actionCompact)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionFileExit)
        self.menu_Cards.addAction(self.actionAddCards)
        self.menu_Cards.addAction(self.actionEditCurrentCard)
        self.menu_Cards.addAction(self.actionDeleteCurrentCard)
        self.menu_Cards.addSeparator()
        self.menu_Cards.addAction(self.actionBrowseCards)
        self.menu_Cards.addAction(self.actionActivateCards)
        self.menu_Cards.addAction(self.actionFindDuplicates)
        self.menu_Cards.addAction(self.actionManageTypes)
        self.menu_Cards.addSeparator()
        self.menu_Cards.addAction(self.actionShowStatistics)
        self.menu_bar.addAction(self.menuFile.menuAction())
        self.menu_bar.addAction(self.menu_Cards.menuAction())
        self.menu_bar.addAction(self.menu_Settings.menuAction())
        self.menu_bar.addAction(self.menu_Help.menuAction())
        self.tool_bar.addAction(self.actionAddCards)
        self.tool_bar.addAction(self.actionEditCurrentCard)
        self.tool_bar.addAction(self.actionDeleteCurrentCard)
        self.tool_bar.addAction(self.actionBrowseCards)
        self.tool_bar.addAction(self.actionShowStatistics)

        self.retranslateUi(MainWdgt)
        QtCore.QObject.connect(self.actionAddCards, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.add_cards)
        QtCore.QObject.connect(self.actionFileNew, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.file_new)
        QtCore.QObject.connect(self.actionFileOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.file_open)
        QtCore.QObject.connect(self.actionFileSave, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.file_save)
        QtCore.QObject.connect(self.actionFileSaveAs, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.file_save_as)
        QtCore.QObject.connect(self.actionFileExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.close)
        QtCore.QObject.connect(self.actionEditCurrentCard, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.edit_current_card)
        QtCore.QObject.connect(self.actionDeleteCurrentCard, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.delete_current_card)
        QtCore.QObject.connect(self.actionManagePlugins, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.manage_plugins)
        QtCore.QObject.connect(self.actionManageTypes, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.manage_card_types)
        QtCore.QObject.connect(self.actionShowStatistics, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.show_statistics)
        QtCore.QObject.connect(self.actionImport, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.import_file)
        QtCore.QObject.connect(self.actionExport, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.export_file)
        QtCore.QObject.connect(self.actionConfigure, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.configure)
        QtCore.QObject.connect(self.actionActivateCards, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.activate_cards)
        QtCore.QObject.connect(self.actionSync, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.sync)
        QtCore.QObject.connect(self.actionBrowseCards, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.browse_cards)
        QtCore.QObject.connect(self.actionTip, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.show_tip)
        QtCore.QObject.connect(self.actionGettingStarted, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.show_getting_started)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.show_about)
        QtCore.QObject.connect(self.actionCompact, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.compact_database)
        QtCore.QObject.connect(self.actionFindDuplicates, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWdgt.find_duplicates)
        QtCore.QMetaObject.connectSlotsByName(MainWdgt)

    def retranslateUi(self, MainWdgt):
        self.menu_Settings.setTitle(_('&Settings'))
        self.menu_Help.setTitle(_('&Help'))
        self.menuFile.setTitle(_('&File'))
        self.menu_Cards.setTitle(_('&Cards'))
        self.tool_bar.setWindowTitle(_('toolBar'))
        self.actionActivateCards.setText(_('(De)a&ctivate cards...'))
        self.actionActivateCards.setShortcut(_('Ctrl+D'))
        self.actionAddCards.setText(_('&Add cards...'))
        self.actionAddCards.setShortcut(_('Ctrl+A'))
        self.actionConfigure.setText(_('&Configure Mnemosyne...'))
        self.actionDeleteCurrentCard.setText(_('&Delete current card'))
        self.actionDeleteCurrentCard.setShortcut(_('Del'))
        self.actionEditCurrentCard.setText(_('&Edit current card...'))
        self.actionEditCurrentCard.setShortcut(_('Ctrl+E'))
        self.actionBrowseCards.setText(_('&Browse cards...'))
        self.actionBrowseCards.setShortcut(_('Ctrl+B'))
        self.actionExport.setText(_('&Export...'))
        self.actionFileExit.setText(_('E&xit'))
        self.actionFileNew.setText(_('&New...'))
        self.actionFileNew.setShortcut(_('Ctrl+N'))
        self.actionFileOpen.setText(_('&Open...'))
        self.actionFileOpen.setShortcut(_('Ctrl+O'))
        self.actionFileSave.setText(_('&Save'))
        self.actionFileSave.setShortcut(_('Ctrl+S'))
        self.actionFileSaveAs.setText(_('Save &as...'))
        self.actionAbout.setText(_('&About'))
        self.actionImport.setText(_('&Import...'))
        self.actionGettingStarted.setText(_('&Getting started'))
        self.actionShowStatistics.setText(_('Show s&tatistics...'))
        self.actionShowStatistics.setShortcut(_('Ctrl+T'))
        self.actionTip.setText(_('&Tip of the day'))
        self.actionManagePlugins.setText(_('Manage &plugins...'))
        self.actionManagePlugins.setToolTip(_('Manage plugins'))
        self.actionManageTypes.setText(_('&Manage card types...'))
        self.actionSync.setText(_('S&ync...'))
        self.actionSync.setShortcut(_('Ctrl+Y'))
        self.actionCompact.setText(_('Compact...'))
        self.actionCompact.setToolTip(_('Compact database'))
        self.actionFindDuplicates.setText(_('Find duplicates'))

import mnemosyne_rc
